name: FarmFresh iOS Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14 # Sonoma

    timeout-minutes: 45

    env:
      NODE_OPTIONS: "--max-old-space-size=4096"
      RCT_NEW_ARCH_ENABLED: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'yarn'

      - name: Add symlink for Node.js (Hermes fix)
        run: |
          sudo ln -sf $(which node) /usr/local/bin/node

      - name: Setup Ruby 3.1.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Setup Xcode 15.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Install yarn dependencies
        run: |
          yarn install --frozen-lockfile
          cd ios && pod install --repo-update && cd ..

      - name: Install Boost and Folly fixes
        run: |
          brew install boost
          export CPATH=$(brew --prefix boost)/include:$CPATH
          [ -d "$HOME/Library/Caches/CocoaPods" ] || pod setup

      - name: Build iOS (Simulator)
        run: |
          cd ios
          xcodebuild clean
          xcodebuild build \
            -workspace FarmFresh_Farmer.xcworkspace \
            -scheme FarmFresh_Farmer \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty

      - name: Build .ipa (AdHoc)
        if: always()
        run: |
          cd ios
          xcodebuild archive \
            -workspace FarmFresh_Farmer.xcworkspace \
            -scheme FarmFresh_Farmer \
            -configuration Release \
            -archivePath $PWD/build/FarmFresh_Farmer.xcarchive \
            -destination generic/platform=iOS \
            CODE_SIGNING_ALLOWED=NO

          xcodebuild -exportArchive \
            -archivePath $PWD/build/FarmFresh_Farmer.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist $PWD/ExportOptions.plist \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: |
            ios/build/Build/Products/**/*.app
            ios/build/*.ipa
          if-no-files-found: warn
